### ISSUE TITLE
no option to delete

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#19]
after booking the room, there is no option to cancel the requested order.

![bug12](https://user-images.githubusercontent.com/81345125/118157866-cb7cf900-b43a-11eb-84fb-2399e860e537.png)

**Comment by ghost** [comment]
Adding link to the cancel button allows users to cancel their bookings.

![Screenshot (979)](https://user-images.githubusercontent.com/81345329/118160525-22d09880-b43e-11eb-98fb-84a21817e26c.png)

Here's a screenshot of the cancel button.
![2021-05-13 (3)](https://user-images.githubusercontent.com/81345329/118160485-164c4000-b43e-11eb-93a2-1759e04e25c2.png)

**Comment by shru9336** [comment]
To address this issue, I added a from field with a limitation for booking are equal to the number of available rooms.

![Screenshot (957)](https://user-images.githubusercontent.com/81345329/118162200-32e97780-b440-11eb-8119-07516a448304.png)

The screenshot above shows that 94 is its final limitation. So that, user cannot add rooms more than 94.

![Screenshot (981)](https://user-images.githubusercontent.com/81345329/118162188-311fb400-b440-11eb-8270-ab96d0b9a561.png)
